services:
  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - "postgres:postgres"
    ports:
      - 6767:6767

  postgres:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blg317e
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 127.0.0.1:1234:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d blg317e"]
      interval: 5s
      timeout: 5s
      retries: 5
